import React,{useEffect,useState} from "react";
import {Edit3,Plus,Target,Trash2,WalletCards} from "lucide-react";
import {budgetApi,categoryApi} from "../api";
import {Badge,EmojiIcon,ErrorBox,Field,FormActions,Modal,PageHeader,SuccessBox,Table,getUser,money,today} from "../components";
const blank={amount:"",period:"MONTHLY",startDate:today(),endDate:"",categoryId:""};
export default function Budgets(){
 const user=getUser(),[rows,setRows]=useState([]),[cats,setCats]=useState([]),[modal,setModal]=useState(null),[form,setForm]=useState(blank),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=async()=>{try{setRows((await budgetApi.list(user.userId)).data||[])}catch(e){setError(e.message)}};useEffect(()=>{Promise.all([load(),categoryApi.list(user.userId)]).then(([_,c])=>setCats(c.data||[])).catch(e=>setError(e.message))},[]);
 const open=r=>{setForm(r?{amount:r.amount,period:r.period,startDate:r.startDate,endDate:r.endDate,categoryId:r.categoryId||"",id:r.budgetId}:{...blank,endDate:new Date(new Date().getFullYear(),new Date().getMonth()+1,0).toISOString().slice(0,10)});setModal(r||{})};
 const save=async e=>{e.preventDefault();try{const b={userId:user.userId,amount:Number(form.amount),period:form.period,startDate:form.startDate,endDate:form.endDate,categoryId:form.categoryId?Number(form.categoryId):null};form.id?await budgetApi.update(user.userId,form.id,b):await budgetApi.create(b);setSuccess("Budget saved.");setModal(null);load()}catch(e){setError(e.message)}};
 const remove=async id=>{if(!confirm("Delete this budget?"))return;try{await budgetApi.remove(user.userId,id);setSuccess("Budget deleted.");load()}catch(e){setError(e.message)}};
 return <div><PageHeader eyebrow="SPENDING GUARDRAILS" title={<span className="title-with-emoji">Budgets <EmojiIcon emoji="💰" label="money bag" size={40} /></span>} description="Give your money a boundary before the month gives you a surprise." action={<button className="primary-btn" onClick={()=>open()}><Plus size={17}/> New budget</button>}/><ErrorBox message={error}/><SuccessBox message={success}/><div className="budget-grid">{rows.map(r=>{const pct=Math.min(100,Number(r.amount)?Number(r.spentAmount)/Number(r.amount)*100:0);return <div className={`budget-card ${r.exceeded?"exceeded":""}`} key={r.budgetId}><div className="budget-head"><div className="budget-icon"><WalletCards size={19}/></div><div><b>{r.categoryName||"Overall spending"}</b><small>{r.period} · {r.startDate} to {r.endDate}</small></div><div className="row-actions"><button className="icon-btn" onClick={()=>open(r)}><Edit3 size={15}/></button><button className="icon-btn danger" onClick={()=>remove(r.budgetId)}><Trash2 size={15}/></button></div></div><div className="budget-values"><strong>{money(r.spentAmount)}</strong><span>of {money(r.amount)}</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="budget-foot"><span>{r.exceeded?<Badge tone="red">Exceeded</Badge>:<Badge tone={pct>80?"orange":"green"}>{money(r.remainingAmount)} left</Badge>}</span><small>{Math.round(pct)}% used</small></div></div>})}{!rows.length&&<div className="panel"><div className="empty"><b>No budgets yet</b><small>Create a monthly or yearly spending limit.</small></div></div>}</div>{modal&&<Modal title={modal.budgetId?"Edit budget":"Create budget"} onClose={()=>setModal(null)}><form onSubmit={save}><div className="form-grid"><Field label="Limit (₹)" required><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Period" required><select value={form.period} onChange={e=>setForm({...form,period:e.target.value})}><option>MONTHLY</option><option>YEARLY</option></select></Field></div><div className="form-grid"><Field label="Start date" required><input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field><Field label="End date" required><input required type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></Field></div><Field label="Category (optional)"><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">All categories</option>{cats.map(c=><option key={c.categoryId} value={c.categoryId}>{c.name}</option>)}</select></Field><FormActions onCancel={()=>setModal(null)} saveLabel="Save budget"/></form></Modal>}</div>
}