import React,{useEffect,useState} from "react";
import {Edit3,Plus,Tags,Trash2} from "lucide-react";
import {categoryApi} from "../api";
import {Badge,EmojiIcon,ErrorBox,Field,FormActions,Modal,PageHeader,SuccessBox,Table,getUser} from "../components";
const blank={name:"",type:"EXPENSE",description:""};
export default function Categories(){
 const user=getUser(),[rows,setRows]=useState([]),[modal,setModal]=useState(null),[form,setForm]=useState(blank),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=async()=>{try{setRows((await categoryApi.list(user.userId)).data||[])}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);
 const open=r=>{setForm(r?{name:r.name,type:r.type||"EXPENSE",description:r.description||"",id:r.categoryId}:blank);setModal(r||{})};
 const save=async e=>{e.preventDefault();try{const b={userId:user.userId,name:form.name.trim(),type:form.type,description:form.description||null};form.id?await categoryApi.update(user.userId,form.id,b):await categoryApi.create(b);setSuccess("Category saved.");setModal(null);load()}catch(e){setError(e.message)}};
 const remove=async id=>{if(!confirm("Delete this category? Existing transactions may prevent deletion."))return;try{await categoryApi.remove(user.userId,id);setSuccess("Category deleted.");load()}catch(e){setError(e.message)}};
 return <div><PageHeader eyebrow="ORGANIZE" title={<span className="title-with-emoji">Categories <EmojiIcon emoji="🏷️" label="label" size={40} /></span>} description="Shape your spending vocabulary so dashboards and reports stay meaningful." action={<button className="primary-btn" onClick={()=>open()}><Plus size={17}/> New category</button>}/><ErrorBox message={error}/><SuccessBox message={success}/><Table rows={rows} empty="No categories yet." columns={[{key:"name",label:"Category",render:r=><div><b>{r.name}</b><small className="table-sub">{r.description||"No description"}</small></div>},{key:"type",label:"Type",render:r=><Badge tone={r.type==="INCOME"?"green":"orange"}>{r.type||"—"}</Badge>},{key:"categoryId",label:"ID"},{key:"actions",label:"",render:r=><div className="row-actions"><button className="icon-btn" onClick={()=>open(r)}><Edit3 size={15}/></button><button className="icon-btn danger" onClick={()=>remove(r.categoryId)}><Trash2 size={15}/></button></div>}]}/>{modal&&<Modal title={modal.categoryId?"Edit category":"Create category"} onClose={()=>setModal(null)}><form onSubmit={save}><Field label="Name" required><input required maxLength="80" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Food & groceries"/></Field><Field label="Type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>EXPENSE</option><option>INCOME</option></select></Field><Field label="Description"><textarea rows="3" maxLength="255" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><FormActions onCancel={()=>setModal(null)} saveLabel="Save category"/></form></Modal>}</div>
}