import React,{useState} from "react";
import {Save,Settings2} from "lucide-react";
import {userApi} from "../api";
import {EmojiIcon,ErrorBox,Field,PageHeader,SuccessBox,getUser,initials} from "../components";
import {setUser} from "../App";
export default function Profile(){
 const current=getUser(),[form,setForm]=useState({name:current.name,email:current.email,phone:current.phone||""}),[error,setError]=useState(""),[success,setSuccess]=useState(""),[saving,setSaving]=useState(false);
 const save=async e=>{e.preventDefault();setSaving(true);try{const u=(await userApi.update(current.userId,form)).data;setUser(u);window.dispatchEvent(new Event("expense-user-changed"));setSuccess("Profile updated successfully.");setError("")}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <div><PageHeader eyebrow="YOUR IDENTITY" title={<span className="title-with-emoji">Profile & settings <EmojiIcon emoji="👤" label="person" size={40} /></span>} description="Your account details are stored by the backend and used to scope every financial record."/><ErrorBox message={error}/><SuccessBox message={success}/><div className="profile-grid"><section className="panel profile-hero"><div className="profile-avatar">{initials(current.name)}</div><span className="eyebrow">ACCOUNT</span><h2>{current.name}</h2><p>{current.email}</p><div className="profile-meta"><span><b>User ID</b>{current.userId}</span><span><b>Created</b>{current.createdAt?new Date(current.createdAt).toLocaleDateString("en-IN"):"—"}</span></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">PERSONAL DETAILS</span><h3>Keep your profile current</h3></div></div><form onSubmit={save}><Field label="Full name" required><input required maxLength="100" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Email" required><input required type="email" maxLength="150" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Phone"><input maxLength="20" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><button className="primary-btn" disabled={saving}>{saving?"Saving…":"Save changes"}<Save size={16}/></button></form></section></div></div>
}