import React,{useEffect,useState} from "react";
import {Edit3,Plus,Repeat2,Trash2} from "lucide-react";
import {recurringApi,categoryApi} from "../api";
import {Badge,EmojiIcon,ErrorBox,Field,FormActions,Modal,PageHeader,SuccessBox,Table,dateFmt,getUser,money,today} from "../components";
const methods=["CASH","UPI","CREDIT_CARD","DEBIT_CARD","BANK_TRANSFER","NET_BANKING","WALLET","OTHER"];
const blank={amount:"",description:"",paymentMethod:"UPI",nextDueDate:today(),active:true,categoryId:""};
export default function Recurring(){
 const user=getUser(),[rows,setRows]=useState([]),[cats,setCats]=useState([]),[modal,setModal]=useState(null),[form,setForm]=useState(blank),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=async()=>{try{setRows((await recurringApi.list(user.userId)).data||[])}catch(e){setError(e.message)}};useEffect(()=>{Promise.all([load(),categoryApi.list(user.userId)]).then(([_,c])=>setCats(c.data||[])).catch(e=>setError(e.message))},[]);
 const open=r=>{setForm(r?{amount:r.amount,description:r.description,paymentMethod:r.paymentMethod,nextDueDate:r.nextDueDate,active:r.active,categoryId:r.categoryId,id:r.recurringExpenseId}:blank);setModal(r||{})};
 const save=async e=>{e.preventDefault();try{const b={userId:user.userId,amount:Number(form.amount),description:form.description.trim(),paymentMethod:form.paymentMethod,nextDueDate:form.nextDueDate,active:form.active,categoryId:Number(form.categoryId)};form.id?await recurringApi.update(user.userId,form.id,b):await recurringApi.create(b);setSuccess("Recurring expense saved.");setModal(null);load()}catch(e){setError(e.message)}};
 const remove=async id=>{if(!confirm("Delete this recurring expense?"))return;try{await recurringApi.remove(user.userId,id);setSuccess("Recurring expense deleted.");load()}catch(e){setError(e.message)}};
 return <div><PageHeader eyebrow="AUTOPILOT" title={<span className="title-with-emoji">Recurring expenses <EmojiIcon emoji="🔄" label="repeat" size={40} /></span>} description="Keep subscriptions, rent and repeat bills visible before they hit." action={<button className="primary-btn" onClick={()=>open()}><Plus size={17}/> Add recurring</button>}/><ErrorBox message={error}/><SuccessBox message={success}/><Table rows={rows} empty="No recurring expenses yet." columns={[{key:"description",label:"Description",render:r=><div><b>{r.description}</b><small className="table-sub">{r.categoryName}</small></div>},{key:"amount",label:"Amount",render:r=><b>{money(r.amount)}</b>},{key:"paymentMethod",label:"Payment",render:r=><Badge>{r.paymentMethod}</Badge>},{key:"nextDueDate",label:"Next due",render:r=>dateFmt(r.nextDueDate)},{key:"active",label:"Status",render:r=><Badge tone={r.active?"green":"neutral"}>{r.active?"ACTIVE":"PAUSED"}</Badge>},{key:"actions",label:"",render:r=><div className="row-actions"><button className="icon-btn" onClick={()=>open(r)}><Edit3 size={15}/></button><button className="icon-btn danger" onClick={()=>remove(r.recurringExpenseId)}><Trash2 size={15}/></button></div>}]}/>{modal&&<Modal title={modal.recurringExpenseId?"Edit recurring expense":"Add recurring expense"} onClose={()=>setModal(null)}><form onSubmit={save}><div className="form-grid"><Field label="Amount (₹)" required><input required type="number" min=".01" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Next due" required><input required type="date" value={form.nextDueDate} onChange={e=>setForm({...form,nextDueDate:e.target.value})}/></Field></div><Field label="Description" required><input required maxLength="150" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="form-grid"><Field label="Category" required><select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Choose</option>{cats.map(c=><option key={c.categoryId} value={c.categoryId}>{c.name}</option>)}</select></Field><Field label="Payment" required><select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></Field></div><label className="check-field"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span>Active recurring item</span></label><FormActions onCancel={()=>setModal(null)} saveLabel="Save recurring"/></form></Modal>}</div>
}