import React,{useEffect,useMemo,useState} from "react";
import {ArrowDownLeft,ArrowUpRight,Download,Edit3,Filter,Plus,Trash2,X} from "lucide-react";
import {categoryApi,expenseApi,incomeApi,dashboardApi} from "../api";
import {Badge,EmojiIcon,ErrorBox,Field,FormActions,Modal,PageHeader,SearchBox,SuccessBox,Table,dateFmt,getUser,money,today,monthStart} from "../components";
const methods=["CASH","UPI","CREDIT_CARD","DEBIT_CARD","BANK_TRANSFER","NET_BANKING","WALLET","OTHER"];
const blank={amount:"",description:"",date:today(),paymentMethod:"UPI",categoryId:""};
export default function Transactions(){
 const user=getUser(),[rows,setRows]=useState([]),[cats,setCats]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState(""),[kind,setKind]=useState("EXPENSE"),[modal,setModal]=useState(null),[form,setForm]=useState(blank),[search,setSearch]=useState(""),[filters,setFilters]=useState({fromDate:monthStart(),toDate:today(),categoryId:"",paymentMethod:"",minAmount:"",maxAmount:"",type:""}),[showFilters,setShowFilters]=useState(true);
 const load=async()=>{setLoading(true);try{const p={...filters};Object.keys(p).forEach(k=>{if(!p[k])delete p[k]});const data=(await dashboardApi.transactions(user.userId,p)).data;setRows(data||[]);setError("")}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{(async()=>{try{setCats((await categoryApi.list(user.userId)).data||[])}catch(e){setError(e.message)};load()})()},[]); useEffect(()=>{if(new URLSearchParams(window.location.search).get("new")==="expense"&&cats.length){openNew("EXPENSE")}},[cats.length]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.description} ${r.categoryName} ${r.paymentMethod}`.toLowerCase().includes(search.toLowerCase())),[rows,search]); const exportCsv=()=>{const head=["Date","Description","Category","Type","Payment","Amount"];const lines=[head,...filtered.map(r=>[r.date,r.description,r.categoryName||"",r.type,r.paymentMethod,r.amount])].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","));const blob=new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`spendwise-transactions-${today()}.csv`;a.click();URL.revokeObjectURL(url)};
 const openNew=(k)=>{
  const matching= cats.filter(c=>(c.type||"").toUpperCase()===k);
  setKind(k);
  setForm({...blank,categoryId:matching[0]?.categoryId||""});
  setModal({});
};
 const openEdit=r=>{setKind(r.type);setForm({amount:r.amount,description:r.description,date:r.date,paymentMethod:r.paymentMethod,categoryId:r.categoryId,id:r.id});setModal(r)};
 const save=async e=>{e.preventDefault();setError("");try{const body={userId:user.userId,amount:Number(form.amount),description:form.description.trim(),[kind==="EXPENSE"?"expenseDate":"incomeDate"]:form.date,paymentMethod:form.paymentMethod,categoryId:Number(form.categoryId)};if(kind==="EXPENSE"){modal?.id?await expenseApi.update(user.userId,modal.id,body):await expenseApi.create(body)}else{modal?.id?await incomeApi.update(user.userId,modal.id,body):await incomeApi.create(body)}setSuccess(`${kind==="EXPENSE"?"Expense":"Income"} saved successfully.`);setModal(null);load()}catch(e){setError(e.message)}};
 const remove=async r=>{if(!confirm(`Delete this ${r.type.toLowerCase()}?`))return;try{if(r.type==="EXPENSE")await expenseApi.remove(user.userId,r.id);else await incomeApi.remove(user.userId,r.id);setSuccess("Transaction deleted.");load()}catch(e){setError(e.message)}};
 return <div>
  <PageHeader eyebrow="MONEY MOVEMENT" title={<span className="title-with-emoji">Transactions <EmojiIcon emoji="💸" label="money movement" size={40} /></span>} description="Capture income and expenses, then filter the story down to exactly what you need." action={<div className="button-row"><button className="soft-btn" onClick={()=>openNew("INCOME")}><ArrowUpRight size={16}/> Income</button><button className="primary-btn" onClick={()=>openNew("EXPENSE")}><ArrowDownLeft size={16}/> Expense</button></div>}/>
  <ErrorBox message={error}/><SuccessBox message={success}/>
  <div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search description, category or payment…"/><button className="soft-btn" onClick={()=>setShowFilters(x=>!x)}><Filter size={16}/> Filters</button><button className="soft-btn" onClick={exportCsv} disabled={!filtered.length}><Download size={16}/> Export CSV</button><span className="toolbar-meta">{filtered.length} transactions</span></div>
  {showFilters&&<div className="filter-card"><Field label="From"><input type="date" value={filters.fromDate} onChange={e=>setFilters({...filters,fromDate:e.target.value})}/></Field><Field label="To"><input type="date" value={filters.toDate} onChange={e=>setFilters({...filters,toDate:e.target.value})}/></Field><Field label="Type"><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">All</option><option>INCOME</option><option>EXPENSE</option></select></Field><Field label="Category"><select value={filters.categoryId} onChange={e=>setFilters({...filters,categoryId:e.target.value})}><option value="">All</option>{cats.map(c=><option key={c.categoryId} value={c.categoryId}>{c.name}</option>)}</select></Field><Field label="Payment"><select value={filters.paymentMethod} onChange={e=>setFilters({...filters,paymentMethod:e.target.value})}><option value="">All</option>{methods.map(m=><option key={m}>{m}</option>)}</select></Field><Field label="Min ₹"><input type="number" min="0" value={filters.minAmount} onChange={e=>setFilters({...filters,minAmount:e.target.value})}/></Field><Field label="Max ₹"><input type="number" min="0" value={filters.maxAmount} onChange={e=>setFilters({...filters,maxAmount:e.target.value})}/></Field><div className="filter-actions"><button className="primary-btn small" onClick={load}>Apply</button><button className="icon-btn" onClick={()=>{setFilters({fromDate:"",toDate:"",categoryId:"",paymentMethod:"",minAmount:"",maxAmount:"",type:""});setTimeout(load,0)}}><X size={16}/></button></div></div>}
  <Table rows={filtered} empty={loading?"Loading…":"No transactions in this range."} columns={[
   {key:"date",label:"Date",render:r=>dateFmt(r.date)},{key:"description",label:"Description",render:r=><div><b>{r.description}</b><small className="table-sub">{r.categoryName}</small></div>},{key:"type",label:"Type",render:r=><Badge tone={r.type==="INCOME"?"green":"orange"}>{r.type}</Badge>},{key:"paymentMethod",label:"Payment",render:r=><Badge>{r.paymentMethod}</Badge>},{key:"amount",label:"Amount",render:r=><b className={r.type==="INCOME"?"amount-income":"amount-expense"}>{r.type==="INCOME"?"+":"−"}{money(r.amount)}</b>},{key:"actions",label:"",render:r=><div className="row-actions"><button className="icon-btn" onClick={()=>openEdit(r)}><Edit3 size={15}/></button><button className="icon-btn danger" onClick={()=>remove(r)}><Trash2 size={15}/></button></div>}
  ]}/>
  {modal&&<Modal title={`${modal.id?"Edit":"Add"} ${kind==="EXPENSE"?"expense":"income"}`} onClose={()=>setModal(null)}><form onSubmit={save}><div className="form-grid"><Field label="Amount (₹)" required><input required min="0.01" step="0.01" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label={kind==="EXPENSE"?"Expense date":"Income date"} required><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field></div><Field label="Description" required><input required maxLength="150" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="e.g. Grocery shopping"/></Field><div className="form-grid"><Field label="Category" required><select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Choose category</option>{cats.filter(c=>(c.type||"").toUpperCase()===kind).map(c=><option key={c.categoryId} value={c.categoryId}>{c.name}</option>)}</select></Field><Field label="Payment method" required><select required value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></Field></div><FormActions onCancel={()=>setModal(null)} saveLabel="Save transaction"/></form></Modal>}
 </div>
}